require 'main_bot/commands/about'
require 'main_bot/commands/help'
require 'main_bot/commands/youtube'
require 'main_bot/supports/about'
require 'main_bot/supports/help'
require 'main_bot/supports/youtube'
